### ISSUE TITLE
EtsyV2 object has no attribut etsy_oauth_client

### ISSUE THREAD

**Issue by gimlithepirate** [mcfunley/etsy-python#3]
Etsy recently updated their API and now there is an attribute error "'EtsyV2' object has no attribute 'etsy_oauth_client'. I went through and fixed all the base references for the URL's to the current version,  but it appears there are still problems. This was when running api = Etsy(yourapikey) from the ReadMe. Not sure what is going on here, especially as I am new to the Etsy API, but any thoughts/help would be appreciated.

**Comment by alekstorm** [comment]
Fixed by #5.

**Comment by djhedges** [comment]
This is still an issue, or perhaps a new one.

/tmp/etsy-python-master/etsy/_v2.pyc in _get_url(self, url, http_method, content_type, body)
     23 
     24     def _get_url(self, url, http_method, content_type, body):
---> 25         return self.etsy_oauth_client.do_oauth_request(url, http_method, content_type, body)
     26 

AttributeError: 'EtsyV2' object has no attribute 'etsy_oauth_client'
